on: 
  pull_request:
  push:
    branches: [main]

jobs:
  deploy-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
      id-token: write # required by npm for publishing package
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 'lts/*'
      
      # install deno to run the decaf scripts in my deploy script.
      # some of the scripts have broken npx or curl install bugs so deno is required to run them.
      - uses: denoland/setup-deno@v2

      - uses: levibostian/decaf@82cd55755480ddd25ed18672ff1166d90bfa426d # 0.13.0
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases-release-branch get --release-branch latest
          get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
          deploy: deno run --allow-all --quiet ./scripts/deploy.ts