on: 
  pull_request:
  push:
    branches: [main]

jobs:
  deploy-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
      id-token: write # required by npm for publishing package
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 'lts/*'
      
      # install deno to run the decaf scripts in my deploy script.
      # some of the scripts have broken npx or curl install bugs so deno is required to run them.
      - uses: denoland/setup-deno@v2

      - uses: levibostian/decaf@366970ed9e5059c9a9cf3b3237b3f19dfa0369ad # 0.17.3
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases-release-branch get --release-branch latest
          get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
          deploy: |
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-git merge-into-release-branch --release-branch latest --merge-options="--ff"
            npm ci 
            npm run compile
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-git commit-and-push --add dist
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-major-tag --tag-prefix v
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases-release-branch set --release-branch latest