on: 
  pull_request:
  push:
    branches: [main]

jobs:
  deploy-action:
    runs-on: ubuntu-latest
    permissions:
      contents: write # If your deploy script that you write needs to push a git commit, git tag, or create a GitHub Release.
      pull-requests: write # If you enable pull request comments (they are enabled by default).
      id-token: write # required by npm for publishing package
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - uses: levibostian/decaf@0.13.0
        env:
          # required to use 'gh' CLI in my step scripts. 
          GH_TOKEN: ${{ github.token }}      
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: |
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases get
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-release-branch get --release-branch latest --version-name {{ versionName }}
          get_next_release_version: deno run --allow-all --quiet jsr:@levibostian/decaf-script-conventional-commits
          # running a git command that's passed to the github releases script to get the latest commit hash for the branch 'latest' because release-branch script creates new commits. 
          deploy: |
            npm ci
            npm run compile
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-release-branch set --release-branch latest --files dist --commit-message "chore: release {{ versionName }}"
            COMMIT_SHA=$(deno run --allow-all --quiet jsr:@levibostian/decaf-script-release-branch latest-commit --release-branch latest)
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-major-tag --commit-sha $COMMIT_SHA
            deno run --allow-all --quiet jsr:@levibostian/decaf-script-github-releases set --generate-notes --latest --target $COMMIT_SHA