name: PR linter 

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]

jobs:
  lint-pr-title:     
    uses: levibostian/action-semantic-pr/.github/workflows/sharable-workflow.yml@make-workflow
    permissions:
      pull-requests: write