name: Run the action from dispatch 

on: 
  workflow_dispatch:
    inputs:
      hide_me:
        description: "This input value should be hidden"
        default: "super-secret-api-key-here"
      exclude_me: 
        description: "This input value should not be hidden"
        default: "This is public info that does not need hidden"
      also_exclude_me: 
        description: "This input value should not be hidden"
        default: "This is public info that does not need hidden"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Install dependencies because I dont want to setup ncc yet 
      run: npm ci 
      
    - uses: ./ 
      with:
        exclude_inputs: "exclude_me, also_exclude_me"
    
    - name: Print all inputs, via inputs, to see if they are hidden 
      run: |
        echo "Value should be hidden: ${{ inputs.hide_me }}"
        echo "Value should be shown: ${{ inputs.exclude_me }}"
        echo "Value should be shown: ${{ inputs.also_exclude_me }}"

    - name: Print all inputs, via a node program, to see if they are hidden 
      uses: actions/github-script@v6  
      with:
        script: |
          core.exportVariable('HIDE_ME', ${{ inputs.hide_me }})
          core.info(`Value should be hidden: process.env.HIDE_ME`)

          core.exportVariable('EXCLUDE_ME', ${{ inputs.exclude_me }})
          core.info(`Value should be shown: process.env.EXCLUDE_ME`)

          core.exportVariable('ALSO_EXCLUDE_ME', ${{ inputs.also_exclude_me }})
          core.info(`Value should be shown: process.env.ALSO_EXCLUDE_ME`)