name: Run the action from dispatch 

on: 
  workflow_dispatch:
    inputs:
      hide_me:
        description: "This input value should be hidden"
        default: "super-secret-api-key-here"
      exclude_me: 
        description: "This input value should not be hidden"
        default: "This is public info that does not need hidden"
      also_exclude_me: 
        description: "This input value should not be hidden"
        default: "This is public info that does not need hidden"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: ./ 
      with:
        exclude_inputs: "exclude_me, also_exclude_me"