name: Test action 

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      actions: write # to be able to call another action in the repo
      contents: read # required for actions/checkout in dispatched workflow
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Trigger workflow that has inputs to hide. Wait for result.
      uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 # v1
      id: test-action
      with:
        workflow: run-action-via-dispatch.yml
        ref: ${{ github.ref_name }} # run the workflow from the current branch to test the present state of the code 
        wait-for-completion: true 
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Assert log contents
      run: node scripts/assert-logs.js
      env:
        RUN_URL: ${{ steps.test-action.outputs.runUrl }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}